### ISSUE TITLE
Can't decode observations from u-blox 6P

### ISSUE THREAD

**Issue by ZiglioNZ** [goGPS-Project/goGPS#11]
I'm having trouble decoding observations from our u-blox evaluation kit.
It's "u-blox 6 GPS Engine", model "EVU-6P-0-001".
goGPS decodes the Ephemeris but I can't see any message being decoded with observations.
It's the first time I try, so I don't know much about different u-blox receiver models and versions.
Any suggestion would be appreciated!

**Comment by nro2dai** [comment]
Emanuele-san,

I have never used "EVK-6P", I use "6T".

How about the receiver has been already activated for RAW data stream using
u-center or others?

Cheers!

2015-06-09 18:04 GMT+09:00 Emanuele Ziglioli <notifications@github.com>:

**Comment by ZiglioNZ** [comment]
Hi @nro2dai 
actually I was wondering if I needed to do something first with u-center.
Are you saying RAW mode needs to be enabled?
I see there's an initialization in UBXSerialReader.start(), I thought those commands would do what's needed. If not, why not?

<pre>
    int nmeaAll[] = { UBXMessageType.NMEA_GGA, UBXMessageType.NMEA_GLL, UBXMessageType.NMEA_GSA, UBXMessageType.NMEA_GSV, UBXMessageType.NMEA_RMC, UBXMessageType.NMEA_VTG, UBXMessageType.NMEA_GRS,
        UBXMessageType.NMEA_GST, UBXMessageType.NMEA_ZDA, UBXMessageType.NMEA_GBS, UBXMessageType.NMEA_DTM };
    for (int i = 0; i < nmeaAll.length; i++) {
      UBXMsgConfiguration msgcfg = new UBXMsgConfiguration(UBXMessageType.CLASS_NMEA, nmeaAll[i], false);
      out.write(msgcfg.getByte());
      out.flush();
    }
</pre>

**Comment by ZiglioNZ** [comment]
Mmm, it seems that my model (LEA-6P-0) doesn't officially support raw data, I'll see if I can shop around for the 6T model. Lots of people with similar questions from the Ardupilot/DIY Drones project:

http://wiki.openstreetmap.org/wiki/UbloxRAW#U-BLOX6

**Comment by ZiglioNZ** [comment]
I'll update with somehow manage to get raw data from this module
